config:
  warningsAsErrors: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

style:
  UnusedPrivateFunction:
    ignoreAnnotated:
      - 'Preview'
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedImport:
    active: true
  WildcardImport:
    active: true

Compose:
  active: true
